name: Deploy to gh-pages

on:
    push:
        branches: [main]
    pull_request:
        branches:
            - main
        types:
            - closed

jobs:
    deploy:
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
              with:
                  persist-credentials: false
            - name: Use Node.js 22
              uses: actions/setup-node@v2
              with:
                  node-version: "22"
            - run: |
                  npm ci
                  npm run build
              # npm run test
            - name: Push dist to gh-pages
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  folder: dist
